apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: ti-engagement-app-api
  description: CICD demo deploy pipeline
serialPipeline:
  stages:
    - targetId: dv
      profiles: [dv]
    - targetId: qa
      profiles: [qa]
    - targetId: pr
      profiles: [pr]

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dv
  description: Development Environment
cloudRun:
  service: dv-cloud-run-service
  region: your-region
executionConfigs:
  - privatePool:
      serviceAccount: 1030302438488-compute@developer.gserviceaccount.com
    usages:
      - DEPLOY
  - defaultPool:
      serviceAccount: 1030302438488-compute@developer.gserviceaccount.com
    usages:
      - RENDER
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qa
  description: Quality Assurance Environment
cloudRun:
  service: qa-cloud-run-service
  region: your-region
executionConfigs:
  - privatePool:
      serviceAccount: 1030302438488-compute@developer.gserviceaccount.com
    usages:
      - DEPLOY
  - defaultPool:
      serviceAccount: 1030302438488-compute@developer.gserviceaccount.com
    usages:
      - RENDER
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: pr
  description: Production Environment
requireApproval: true
cloudRun:
  service: pr-cloud-run-service
  region: your-region
executionConfigs:
  - privatePool:
      serviceAccount: 1030302438488-compute@developer.gserviceaccount.com
    usages:
      - DEPLOY
  - defaultPool:
      serviceAccount: 1030302438488-compute@developer.gserviceaccount.com
    usages:
      - RENDER
