name: Cloud Deploy
run-name: "Deploy ${{ github.ref_name }} to [ ${{ inputs.environment }} ]: ${{ inputs.description }}"
on:
  workflow_dispatch:
    inputs:
      description:
        type: string
        description: "Story number or short description"
        required: true
      environment:
        type: choice
        description: "Select environment"
        required: true
        options:
          - dv
          - qa
          - pr

env:
  SERVICE_NAME: engagement-app-api
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}
  CI: false

jobs:
  cloud-deploy:
    name: cloud deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    permissions:
      contents: "write"
      pull-requests: "write"
      id-token: "write"
    steps:
      - name: "Cloning repo"
        uses: actions/checkout@v3

      - id: tagging
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: "beta"

      - name: Build Docker image
        run: |-
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ steps.tagging.outputs.new_tag }} .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ steps.tagging.outputs.new_tag }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ steps.tagging.outputs.new_tag }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated

      - name: Check deployment status
        run: |-
          gcloud run services describe ${{ env.SERVICE_NAME }} --region ${{ env.REGION }}
